-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.board_members DROP CONSTRAINT IF EXISTS board_members_user_id_fkey;
-- ALTER TABLE public.board_members ADD CONSTRAINT board_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE;
